steps:
  # Docker Build
  - name: 'us-east1-docker.pkg.dev/daring-hash-348101/smu-mle-usa/generatedata'
    args: ['build', '-t', 
           'us-east1-docker.pkg.dev/daring-hash-348101/facemaskcicd-docker-repo/cicd', 
           '.']

  # Docker Push
  - name: 'us-east1-docker.pkg.dev/daring-hash-348101/facemaskcicd-docker-repo/cicd'
    args: ['push', 
           'us-east1-docker.pkg.dev/daring-hash-348101/facemaskcicd-docker-repo/cicd']
